name: Build and deploy Azure Web App

on:
  push:
   branches: [main]
  pull_request:
   branches: [main]
  workflow_dispatch:
  
jobs:
  build_web_app:
    name: Build Web App
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
      
    - name: Setup .NET
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: 3.1.301
      
    - name: Restore dependencies
      run: dotnet restore
      env:
        DOTNET_SYSTEM_GLOBALIZATION_INVARIANT: true
        DOTNET_ROOT: /home/runner/.dotnet
      working-directory: ./Tailspin.SpaceGame.Web
      
    - name: Build
      run: dotnet build --no-restore
      env:
        DOTNET_SYSTEM_GLOBALIZATION_INVARIANT: true
        DOTNET_ROOT: /home/runner/.dotnet
      working-directory: ./Tailspin.SpaceGame.Web
    
    - name: Publish
      run: dotnet publish --no-restore -c Release
      working-directory: ./Tailspin.SpaceGame.Web
    
    - name: Upload a Build Artifact
      uses: actions/upload-artifact@v4
      with:
        name: spacegameweb
        path: ./Tailspin.SpaceGame.Web/bin/Release/netcoreapp3.1/publish/
